---
image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm i

stages:
  - compile
  - build
  - test

lint:
  script:
    - ./bin/lint-all.sh
  stage: compile
  only:
    - master
  tags:
    - docker
    - linux
  allow_failure: false
  when: always

compile:
  script:
    - ./bin/compile-all-test.sh
  stage: compile
  only:
    - master
  tags:
    - docker
    - linux
  allow_failure: false
  when: always

build:
  image: docker/compose:1.24.1
  dependencies:
    - compile
  script:
    - ./bin/build-all-test.sh
  stage: build
  only:
    - master
  tags:
    - docker
    - linux
  allow_failure: false
  when: always

test:
  image: docker/compose:1.24.1
  dependencies:
    - build
  script:
    - ./bin/run-tests.sh
  stage: test
  only:
    - master
  tags:
    - docker
    - linux
  allow_failure: false
  when: always
