---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  namespace: dev
  labels:
    app: graphql-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graphql-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: graphql-gateway
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-pool
                  operator: In
                  values:
                    - internal
      containers:
        - name: graphql-gateway
          image: "graphql-gateway:latest"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 300m
              memory: 300Mi
          envFrom:
            - configMapRef:
                name: graphql-gateway
            - secretRef:
                name: cache
            - secretRef:
                name: jwt
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 10
# ---
# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: graphql-gateway
#   namespace: dev
#   labels:
#     app: graphql-gateway
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     name: graphql-gateway
#     kind: Deployment
#   minReplicas: 3
#   maxReplicas: 10
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         targetAverageUtilization: 60
#     - type: Resource
#       resource:
#         name: memory
#         targetAverageUtilization: 85
